// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxxutwglxbfqesyprvxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eHV0d2dseGJmcWVzeXBydnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzY3MDIsImV4cCI6MjA3MTk1MjcwMn0.6CgKZ6SkdLWmCdyyjVHHLRY6a1LT0o0AeEFGKlribtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});